version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - DB_CONNECTION_STRING=Server=mssql;Database=YourDb;User Id=sa;Password=${DB_PASSWORD}
    ports:
      - "5000:80"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mssql_data:
